kind: Service
apiVersion: v1
metadata:
  name: ${{ values.repo_name }}
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ${{ values.repo_name }}
