apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: obc-template
  title: Add OBC to an existing project
  description: Add OBC to an existing project
  tags:
    - recommended
    - obc
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Provide information about the existing GitHub location
      required:
        - githubOrg
        - repoName
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
        repoName:
          title: Repository Name
          type: string
    - title: Provide information about the new component
      required:
        - owner
        - system
        - storageClassName
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: janus-authors
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - Group
              - User
        system:
          title: System
          type: string
          description: System of the component
          default: examples
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - System
        storageClassName:
          title: Storage Class Name
          type: string
          description: Storage Class Name of the OBC
  steps:
    - id: catalogTemplate
      name: Generating catalog-info.yaml
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        values:
          # Gitops specific values
          applicationKind: Resource

          # Normal values
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}-gitops
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: gitops
          description: Contains the OBC manifests for ${{ parameters.repoName }}

    - id: manifestsTemplate
      name: Generating manifests component
      action: fetch:template
      input:
        url: ./template
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}-gitops
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: gitops
          description: Contains the OBC manifests for ${{ parameters.repoName }}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.githubOrg }}&repo=${{ parameters.repoName }}-gitops
        defaultBranch: main

    - id: register
      name: Registering the component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
