apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: A collection of available Janus-IDP Backstage templates
spec:
  type: file
  targets:
    - ./scaffolder-templates/app-template/template.yaml
    - ./scaffolder-templates/go-runtime-template/template.yaml
    - ./scaffolder-templates/nodejs-backend-template/template.yaml
    - ./scaffolder-templates/quarkus-web-template/template.yaml
