apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: argocd-template
  title: Add ArgoCD to an existing project
  description: Add ArgoCD to an existing project
  tags:
    - recommended
    - argocd
spec:
  owner: janus-authors
  type: service

  parameters:
    - title: Provide information about the existing GitHub location
      required:
        - github_org
        - repo_name
      properties:
        github_org:
          title: GitHub Organization
          type: string
        repo_name:
          title: Repository Name
          type: string
    - title: Provide information about the new component
      required:
        - owner
        - system
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: janus-authors
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - Group
              - User
        system:
          title: System
          type: string
          description: System of the component
          default: examples
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - System
    - title: Provide information about the ArgoCD deployment
      required:
        - image_repository
        - namespace
        - image_url
        - port
      properties:
        image_repository:
          title: Select a registry
          type: string
          default: quay.io
          enum:
            - image-registry.openshift-image-registry.svc:5000
            - quay.io
          enumNames:
            - Internal OpenShift Registry
            - Quay
        image_url:
          title: Image URL
          type: string
          description: Enter the Quay.io or OpenShift Image URL <REGISTRY>/<IMAGE_URL>/<REPO_NAME>
        namespace:
          title: Namespace
          type: string
          default: janus-idp
          description: The namespace for deploying resources
        port:
          title: Port
          type: number
          description: The port exposed for the application
  steps:
    - id: catalog-template
      name: Generating catalog-info.yaml
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        values:
          # Gitops specific values
          application_kind: Resource
          depends_on: ${{ parameters.repo_name }}

          # Normal values
          github_org: ${{ parameters.github_org }}
          repo_name: ${{ parameters.repo_name }}-gitops
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          application_type: gitops
          description: Contains the ArgoCD manifests for ${{ parameters.repo_name }}
          namespace: ${{ parameters.namespace }}
          image_url: ${{ parameters.image_url }}
          image_repository: ${{ parameters.image_repository }}
          port: ${{ parameters.port }}

    - id: manifests-template
      name: Generating manifests component
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/manifests-skeleton/
        values:
          github_org: ${{ parameters.github_org }}
          repo_name: ${{ parameters.repo_name }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          application_type: gitops
          description: Contains the ArgoCD manifests for ${{ parameters.repo_name }}
          namespace: ${{ parameters.namespace }}
          image_url: ${{ parameters.image_url }}
          image_repository: ${{ parameters.image_repository }}
          port: ${{ parameters.port }}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.github_org }}&repo=${{ parameters.repo_name }}-gitops
        defaultBranch: main

    - id: register
      name: Registering the component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
