apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: go-backend-template
  title: Go Backend Golden Path Template
  description: Create a starter Go backend application with a CI pipeline and optionally managed by ArgoCD
  tags:
    - recommended
    - go
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
        - repoName
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
        repoName:
          title: Repository Name
          type: string
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
    - title: Provide information about the new component
      required:
        - owner
        - system
        - applicationType
        - port
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: janus-authors
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - Group
              - User
        system:
          title: System
          type: string
          description: System of the component
          default: examples
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - System
        applicationType:
          title: Application Type
          type: string
          description: The application type e.g. website, api, and gitops
          enum:
            - website
            - api
            - gitops
        port:
          title: Port
          type: number
          default: 8080
          description: The port exposed for the application
    - title: Provide information about the CI method
      required:
        - ci
      properties:
        ci:
          title: Select a CI method
          type: string
          description: This action will create a CI pipeline for your application based on chosen method
          default: ../../scaffolder-skeletons/github-actions-skeleton/
          enum:
            - ../../scaffolder-skeletons/github-actions-skeleton/
            - ../../scaffolder-skeletons/tekton-skeleton/
          enumNames:
            - GitHub Action
            - Tekton
    - title: Provide information about the ArgoCD deployment
      required:
        - useGitops
        - imageRepository
        - namespace
        - imageUrl
      properties:
        useGitops:
          title: Include ArgoCD
          type: boolean
          default: true
          ui:widget: radio
          description: Should the component include a ArgoCD workflow
        imageRepository:
          title: Select a registry
          type: string
          default: quay.io
          enum:
            - image-registry.openshift-image-registry.svc:5000
            - quay.io
          enumNames:
            - Internal OpenShift Registry
            - Quay
        imageUrl:
          title: Image URL
          type: string
          description: Enter the Quay.io or OpenShift Image URL <REGISTRY>/<IMAGE_URL>/<REPO_NAME>
        namespace:
          title: Namespace
          type: string
          default: janus-idp
          description: The namespace for deploying resources
      dependencies:
        useGitops:
          oneOf:
            # We don't want to show any extra properties when ArgoCD isn't selected
            - properties:
                useGitops:
                  const: false
            - required:
                - hostUrl
              properties:
                useGitops:
                  const: true
                hostUrl:
                  title: Host URL
                  type: string
                  description: The external facing host URL
  steps:
    - id: sourceCodeTemplate
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: ${{ parameters.applicationType }}
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          hostUrl: ${{ parameters.hostUrl }}
          imageBuilder: s2i-go
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}

    - id: ciTemplate
      name: Generating the CI component
      action: fetch:template
      input:
        url: ${{ parameters.ci }}
        targetPath: ./source
        copyWithoutTemplating:
          - .github/workflows/
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: ${{ parameters.applicationType }}
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          hostUrl: ${{ parameters.hostUrl }}
          imageBuilder: s2i-go
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}

    - id: catalogTemplate
      name: Generating Source Code catalog-info.yaml
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        targetPath: ./source
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: ${{ parameters.applicationType }}
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          hostUrl: ${{ parameters.hostUrl }}
          imageBuilder: s2i-go
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        sourcePath: ./source
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.githubOrg }}&repo=${{ parameters.repoName }}
        defaultBranch: main

    - id: register
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
