apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-frontend-template
  title: Create a .NET Frontend application with CI/CD
  description: Create a starter .NET frontend application with a CI pipeline and optionally managed by ArgoCD
  tags:
    - recommended
    - dotnet
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
        - repoName
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
        repoName:
          title: Repository Name
          type: string
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
    - title: Provide information about the new component
      required:
        - owner
        - system
        - port
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: janus-authors
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          description: System of the component
          default: examples
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 5000
          description: The port exposed for the application
    - title: Provide information about the CI method
      required:
        - ci
      properties:
        ci:
          title: Select a CI method
          type: string
          description: This action will create a CI pipeline for your application based on chosen method
          default: ../../scaffolder-skeletons/github-actions-skeleton/
          enum:
            - ../../scaffolder-skeletons/github-actions-skeleton/
            - ../../scaffolder-skeletons/tekton-skeleton/
          enumNames:
            - GitHub Action
            - Tekton
      dependencies:
        ci:
          oneOf:
            - properties:
                # Show no extra properties when GitHub Actions is selected
                ci:
                  const: ../../scaffolder-skeletons/github-actions-skeleton/
            - required:
                - imageRepository
                - namespace
                - imageUrl
              properties:
                ci:
                  const: ../../scaffolder-skeletons/tekton-skeleton/
                imageRepository:
                  title: Select a registry
                  type: string
                  default: quay.io
                  enum:
                    - quay.io
                    - image-registry.openshift-image-registry.svc:5000
                  enumNames:
                    - Quay
                    - Internal OpenShift Registry
                imageUrl:
                  title: Image URL
                  type: string
                  description: Enter the Quay.io or OpenShift Image URL <REGISTRY>/<IMAGE_URL>/<REPO_NAME>
                namespace:
                  title: Namespace
                  type: string
                  default: janus-idp
                  description: The namespace for deploying resources
  steps:
    - id: sourceCodeTemplate
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: website
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          hostUrl: ${{ parameters.hostUrl }}
          imageBuilder: s2i-dotnetcore
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}

    - id: ciTemplate
      name: Generating the CI component
      action: fetch:template
      input:
        url: ${{ parameters.ci }}
        targetPath: ./source
        copyWithoutTemplating:
          - .github/workflows/
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: website
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          hostUrl: ${{ parameters.hostUrl }}
          imageBuilder: s2i-dotnetcore
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}

    - id: catalogTemplate
      name: Generating Source Code catalog-info.yaml
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        targetPath: ./source
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: website
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          hostUrl: ${{ parameters.hostUrl }}
          imageBuilder: s2i-dotnetcore
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        sourcePath: ./source
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.githubOrg }}&repo=${{ parameters.repoName }}
        defaultBranch: main

    - id: register
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
