kind: Service
apiVersion: v1
metadata:
  name: ${{ values.repoName }}
spec:
  ports:
    - name: http-${{ values.port }}
      port: ${{ values.port }}
      protocol: TCP
      targetPort: ${{ values.port }}
  selector:
    app: ${{ values.repoName }}
